# Generated by Django 2.0.4 on 2018-05-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[(3, 3), (4, 4), (5, 5), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=2)),
                ('area', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('table', models.CharField(max_length=2)),
                ('seats', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SeatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[(3, 3), (4, 4), (5, 5), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=2)),
                ('area', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('table', models.CharField(max_length=2)),
                ('seats', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6)], max_length=1)),
            ],
        ),
    ]
