# Generated by Django 2.0.4 on 2018-04-18 11:27

from django.db import migrations

def load_initial(apps, schema_editor):
	DefaultSeatInfo = apps.get_model('seats_info','DefaultSeatInfo')
	SeatInfo = apps.get_model('seats_info', 'SeatInfo')

# maybe create a .py file and import this function from that file

	third_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 3, '4_seat': 35, '6_seat': 0}],
	'B': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 53, '6_seat': 0}],
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 20, '6_seat': 0}],
	'D': [{'1_seat': 18, '2_seat':0, '3_seat': 0, '4_seat': 25, '6_seat': 0}],
	'E': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 14, '6_seat': 0}],
	}
	fourth_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 3, '6_seat': 0}],
	'B': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 15, '6_seat': 0}],
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 34, '6_seat': 0}],
	}
	fifth_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 10, '6_seat': 0}],
	'B': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 15, '6_seat': 0}], 
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 32, '6_seat': 0}],
	}
	sixth_floor = {}
	seventh_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 8, '6_seat': 0}],
	'B': [{'1_seat': 0, '2_seat': 14, '3_seat': 0, '4_seat': 0, '6_seat': 11}],
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 7, '6_seat': 0}],
	}
	eighth_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 10, '6_seat': 0}], 
	'B': [{'1_seat': 8, '2_seat':0, '3_seat': 0, '4_seat': 0, '6_seat': 12}], 
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 8, '6_seat': 0}],
	}
	ninth_floor = {
	'A': [{'1_seat': 4, '2_seat':0, '3_seat': 0, '4_seat': 0, '6_seat': 17}], 
	'B': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 7, '6_seat': 0}],
	}
	tenth_floor = {
	'A': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 9, '6_seat': 0}], 
	'B': [{'1_seat': 4, '2_seat':0, '3_seat': 0, '4_seat': 0, '6_seat': 15}], 
	'C': [{'1_seat': 0, '2_seat':0, '3_seat': 0, '4_seat': 8, '6_seat': 0}],
	}

	floor_list = [third_floor, fourth_floor, fifth_floor, sixth_floor, 
	seventh_floor, eighth_floor, ninth_floor, tenth_floor]

	floor_num = 3
	for floor in floor_list:
		if floor != sixth_floor:
			for area in floor.keys():
				seats = floor[area][0]
				#counter = 0
				for seat_type in seats.keys():
					if seats[seat_type] == 0:
						continue
					else:
						num = int(seat_type.split("_")[0])
						#counter = num + counter

					if floor_num == 3 and area == 'A':
						for seat_No in range(1, 14):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
						for seat_No in range(14, 17):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 3).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 3).save()
						for seat_No in range(17, 39):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
						break
					elif floor_num == 3 and area == 'D':
						for seat_No in range(1, 19):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
						for seat_No in range(19, 44):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
						break
					elif floor_num == 7 and area == 'B':
						for seat_No in range(1, 3):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						for seat_No in range(3, 17):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 2).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 2).save()
						for seat_No in range(17, 26):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						break
					elif floor_num == 8 and area == 'B':
						for seat_No in range(1, 3):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						for seat_No in range(3, 11):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
						for seat_No in range(11, 21):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						break
					elif floor_num == 9 and area == 'A':
						for seat_No in range(1, 5):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						for seat_No in range(5, 9):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
						for seat_No in range(9, 22):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 4).save()
						break
					elif floor_num == 10 and area == 'B':
						for seat_No in range(1, 4):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						for seat_No in range(4, 8):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 1).save()
						for seat_No in range(8, 20):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = 6).save()
						break
					else:
						for seat_No in range(1, seats[seat_type]+1):
							DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = num).save()
							SeatInfo(floor = floor_num, area = area, table = seat_No, seats = num).save()

						# for seat_No in range(1, counter + 1):
						# 	DefaultSeatInfo(floor = floor_num, area = area, table = seat_No, seats = num).save()
						# 	SeatInfo(floor = floor_num, area = area, table = seat_No, seats = num).save()

						

		floor_num = floor_num + 1


class Migration(migrations.Migration):

    dependencies = [
        ('seats_info', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_initial)
    ]
